// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg8roam7OddzgQkBKhDffmvhU-h2qylok',
    appId: '1:113017104454:web:c63d58af136f70cf5d4247',
    messagingSenderId: '113017104454',
    projectId: 'taskapp1-61c1e',
    authDomain: 'taskapp1-61c1e.firebaseapp.com',
    storageBucket: 'taskapp1-61c1e.appspot.com',
    measurementId: 'G-9ZFEY2BX0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtyP4EU3ieWwg7KQ7LTJBVBNrr2SOtQtQ',
    appId: '1:113017104454:android:8d3f289ba5fb16515d4247',
    messagingSenderId: '113017104454',
    projectId: 'taskapp1-61c1e',
    storageBucket: 'taskapp1-61c1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAChsb3gfvL2COaFvqipk7Hj_KhFW4v748',
    appId: '1:113017104454:ios:0f160be4347d15775d4247',
    messagingSenderId: '113017104454',
    projectId: 'taskapp1-61c1e',
    storageBucket: 'taskapp1-61c1e.appspot.com',
    iosClientId: '113017104454-agnd89jr4tlfoisd6oasshvrvguioqnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAChsb3gfvL2COaFvqipk7Hj_KhFW4v748',
    appId: '1:113017104454:ios:5d291daffac3b9965d4247',
    messagingSenderId: '113017104454',
    projectId: 'taskapp1-61c1e',
    storageBucket: 'taskapp1-61c1e.appspot.com',
    iosClientId: '113017104454-cno1sbald221ngi86msdodejv8c6e6vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.projet.RunnerTests',
  );
}
